### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI-522_Bank-Marketing#27]
__Mechanics:__

- [ ] Might want to use GitHub issues to communicate within the teams. This is part of the lab requirements... If most of your communications are in-person, you can still open issues to, say, keep track of tasks to do and ideas to be considered.
- [ ] Could have edited the README from the proposal version a little more rather than just adding new items to the list.
- [ ] Maybe add a project overview with a nice 'sale pitch' at the beginning? Make this landing page more inviting to the readers.
- [ ] Might want to add version number for the packages in the dependency section.

__Quality:__
- [ ] Beef up the documentation a little more? Say for `data_loading-clean.py`, instead just showing an example usage, you can explain what the two arguments are.
- [ ] Could have polished table 2 as well. Say, the first row of `X1` and `X2` can be dropped.

__Others:__
- [ ] Going beyond, since you wrote some python functions, would be nice to create unit tests for each of them.
- [ ] no need to capitalize 'cross validation'; probably don't have to capitalize 'decision tree classifer' as well (?)
- [ ] Variables like `months_mar`, `month_jun`, `month_oct`, etc seems to be dummy variables for the categorical feature of month. Say if we are to interpret all these dummy variables as a whole, I wonder how we can report the importance of 'month'.

__Report (Reasoning):__
- [ ] Need to explain what the predictors are, their meanings, data types. Maybe add an introduction section.
- [ ] Try to make the analysis more interpretable to a reader unfamiliar with the data set.
- [ ] Might want to report some simple summary statistics for each variable to give the reader a better picture of the data. 
- [ ] When choosing tree-depth, could have clarified what you mean by 'pick the next best score which is the depth of 6 for the full tree'.
- [ ] Need to mention what fold of CV you used.
- [ ] Need a reference section (see lab instructions)
- [ ] Might want to replace the feature/variable names, in Table 1 and throughout the report, by names in a 'natural language'. Their code names are not always self-explanatory anyway.

__Report (Visualizations):__
- [ ] Ideally, figures and tables should be standalone and interpretable without referring back to text except for some technical details. Some captions would be useful.
- [ ] In particular, for the tree diagram, there needs to be a layman description on how to read the graph.
- [ ] Text in the tree diagram is also too small and difficult to read. Yet, I guess it will be time consuming to write your own function to visualize the tree (?) I wonder if there are any options for what to show in each node...

**Comment by everittB** [comment]
Update final report to address some of the report and reasoning recommendatation. #29
